{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledge-system.secretName" . }}
  labels:
    {{- include "knowledge-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
{{- with .Values.secrets.data }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end -}}
