// Generated by Trae Work
import PptxGenJS from "pptxgenjs";

const pptx = new PptxGenJS();
pptx.layout = "LAYOUT_WIDE"; // 16:9
pptx.title = "知域引擎 - 领域知识个性化生成与多智能体协同决策系统";
pptx.author = "知域引擎项目组";
pptx.company = "上海云之脑智能科技有限公司";

// ============================================================
// 设计令牌 — 咨询研报风格
// ============================================================
const COLORS = {
  ink: "1A1A2E",         // 主文字 - 深蓝黑
  muted: "5A6070",       // 次要文字 - 灰蓝
  accent: "1E5AA8",      // 主强调 - 藏青
  accentLight: "E8F0FA", // 强调浅色背景
  accentFaint: "F0F5FB", // 极浅强调色（替代透明15%）
  accentSoft: "D6E4F5",  // 浅强调色（替代透明30%）
  teal: "0F766E",        // 辅助强调 - 青绿
  tealFaint: "E6F3F1",   // 极浅青（替代透明15%）
  tealSoft: "B8DAD6",    // 浅青（替代透明30%）
  purple: "7C3AED",      // 紫色
  purpleFaint: "F1ECFE", // 极浅紫（替代透明15%）
  purpleSoft: "D9CCF7",  // 浅紫（替代透明30%）
  pink: "DB2777",        // 粉色
  pinkFaint: "FCE7F1",
  pinkSoft: "F5B9D0",
  surface: "FFFFFF",     // 表面白
  surfaceAlt: "F7F8FA",  // 交替表面
  hairline: "E2E5EA",    // 细线 - 浅灰
  grid: "EEF0F4",        // 网格线
  positive: "059669",    // 正面 - 绿
  positiveFaint: "E6F5EF",
  positiveSoft: "A3D9C2",
  caution: "D97706",     // 警告 - 橙
  cautionFaint: "FEF3E0",
  cautionSoft: "F5D5A5",
  risk: "DC2626",        // 风险 - 红
  riskFaint: "FDE7E7",
  riskSoft: "F2B5B5",
  amber: "F59E0B",       // 琥珀色
  amberFaint: "FEF3C7",
  amberSoft: "F9DEB0",
};

const FONTS = {
  head: "Microsoft YaHei",
  body: "Microsoft YaHei",
  mono: "Consolas",
};

const SPACING = {
  marginX: 0.6,
  marginY: 0.45,
  titleGap: 0.35,
  sectionGap: 0.25,
  panelGap: 0.25,
};

// 幻灯片尺寸（英寸）— WIDE 13.333 x 7.5
const SLIDE_W = 13.333;
const SLIDE_H = 7.5;

// ============================================================
// 通用原语
// ============================================================

function addHairline(slide, x, y, w, color = COLORS.hairline) {
  slide.addShape(pptx.ShapeType.line, {
    x, y, w, h: 0,
    line: { color, width: 0.75 },
  });
}

function addSectionLabel(slide, text, x = SPACING.marginX, y = SPACING.marginY) {
  slide.addText(text, {
    x, y, w: 8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 11,
    color: COLORS.muted,
    bold: false,
    charSpacing: 2,
    valign: "middle",
  });
}

function addClaimTitle(slide, text, x = SPACING.marginX, y = 0.85, w = SLIDE_W - SPACING.marginX * 2) {
  slide.addText(text, {
    x, y, w, h: 0.6,
    fontFace: FONTS.head,
    fontSize: 26,
    color: COLORS.ink,
    bold: true,
    valign: "middle",
  });
}

function addAccentBar(slide, x, y, w = 0.08, h = 0.45, color = COLORS.accent) {
  slide.addShape(pptx.ShapeType.rect, {
    x, y, w, h,
    fill: { color },
    line: { color, width: 0 },
  });
}

function addSourceLine(slide, text) {
  slide.addText(text, {
    x: SPACING.marginX,
    y: SLIDE_H - SPACING.marginY - 0.25,
    w: SLIDE_W - SPACING.marginX * 2,
    h: 0.22,
    fontFace: FONTS.body,
    fontSize: 9,
    color: COLORS.muted,
    italic: true,
    valign: "middle",
  });
}

function addPageNumber(slide, num, total = 15) {
  slide.addText(`${num} / ${total}`, {
    x: SLIDE_W - SPACING.marginX - 1.0,
    y: SLIDE_H - SPACING.marginY - 0.25,
    w: 1.0, h: 0.22,
    fontFace: FONTS.body,
    fontSize: 9,
    color: COLORS.muted,
    align: "right",
    valign: "middle",
  });
}

function addFooterRule(slide) {
  addHairline(slide, SPACING.marginX, SLIDE_H - SPACING.marginY - 0.35, SLIDE_W - SPACING.marginX * 2);
}

// 文字徽章 — 替代 emoji，避免编码问题
function addTextBadge(slide, x, y, size, text, bgColor, textColor) {
  slide.addShape(pptx.ShapeType.ellipse, {
    x, y, w: size, h: size,
    fill: { color: bgColor },
    line: { color: bgColor, width: 0 },
  });
  slide.addText(text, {
    x, y, w: size, h: size,
    fontFace: FONTS.head,
    fontSize: Math.round(size * 20),
    color: textColor || "FFFFFF",
    bold: true,
    align: "center",
    valign: "middle",
  });
}

// 单行短代码保护
function addSingleLineToken(slide, text, opts) {
  slide.addText(text, {
    ...opts,
    margin: 0,
    wrap: false,
    vert: "horz",
    fit: "shrink",
  });
}

// 证据面板（带细边框的内容卡片）
function addEvidencePanel(slide, x, y, w, h, options = {}) {
  slide.addShape(pptx.ShapeType.rect, {
    x, y, w, h,
    fill: { color: options.fill || COLORS.surface },
    line: { color: options.lineColor || COLORS.hairline, width: 0.75 },
  });
  if (options.headerColor) {
    slide.addShape(pptx.ShapeType.rect, {
      x, y, w, h: 0.06,
      fill: { color: options.headerColor },
      line: { color: options.headerColor, width: 0 },
    });
  }
}

// ============================================================
// 页面 01 — 封面
// ============================================================
function slide01_cover() {
  const slide = pptx.addSlide();

  // 左侧大色块 — 深蓝
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 5.2, h: SLIDE_H,
    fill: { color: COLORS.ink },
    line: { color: COLORS.ink, width: 0 },
  });

  // 左侧装饰线条
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.8, y: 1.2, w: 0.06, h: 0.8,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 英文小标题
  slide.addText("MULTI-AGENT KNOWLEDGE SYSTEM", {
    x: 0.8, y: 2.2, w: 4.0, h: 0.35,
    fontFace: FONTS.head,
    fontSize: 11,
    color: "8B95A5",
    charSpacing: 3,
    bold: false,
  });

  // 主标题
  slide.addText("知域引擎", {
    x: 0.8, y: 2.65, w: 4.0, h: 1.2,
    fontFace: FONTS.head,
    fontSize: 48,
    color: "FFFFFF",
    bold: true,
  });

  // 副标题
  slide.addText("领域知识个性化生成与\n多智能体协同决策系统", {
    x: 0.8, y: 3.95, w: 4.0, h: 0.9,
    fontFace: FONTS.head,
    fontSize: 18,
    color: "C8D0DC",
    lineSpacing: 1.4,
    bold: false,
  });

  // 底部信息
  slide.addText("v1.0.0  ·  2026", {
    x: 0.8, y: 6.5, w: 4.0, h: 0.3,
    fontFace: FONTS.body,
    fontSize: 10,
    color: "6B7280",
  });

  // 右侧白色区域
  // 右上装饰 — 细线网格
  const gridX = 6.0, gridY = 0.8, cellW = 0.55, cellH = 0.55;
  for (let r = 0; r < 8; r++) {
    for (let c = 0; c < 12; c++) {
      if (Math.random() > 0.72) {
        slide.addShape(pptx.ShapeType.rect, {
          x: gridX + c * cellW, y: gridY + r * cellH,
          w: cellW - 0.04, h: cellH - 0.04,
          fill: { color: "F0F3F7" },
          line: { color: "F0F3F7", width: 0 },
        });
      }
    }
  }

  // 右侧核心价值点
  const rightX = 6.2;
  const points = [
    { num: "01", title: "多智能体协同", desc: "诊断·生成·评判·编排 四轮辩论优化" },
    { num: "02", title: "个性化生成", desc: "学情画像驱动的知识资源定制" },
    { num: "03", title: "幻觉检测", desc: "事实性错误自动识别与纠偏机制" },
    { num: "04", title: "全形态部署", desc: "Docker / K8s / Windows 桌面版" },
  ];

  points.forEach((p, i) => {
    const py = 2.4 + i * 1.1;
    // 序号
    addSingleLineToken(slide, p.num, {
      x: rightX, y: py, w: 0.6, h: 0.45,
      fontFace: FONTS.head,
      fontSize: 22,
      bold: true,
      color: COLORS.accent,
      valign: "top",
    });
    // 标题
    slide.addText(p.title, {
      x: rightX + 0.7, y: py + 0.02, w: 5.5, h: 0.38,
      fontFace: FONTS.head,
      fontSize: 16,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });
    // 描述
    slide.addText(p.desc, {
      x: rightX + 0.7, y: py + 0.42, w: 5.5, h: 0.32,
      fontFace: FONTS.body,
      fontSize: 11,
      color: COLORS.muted,
      valign: "top",
    });
    // 分隔线（最后一条不加）
    if (i < points.length - 1) {
      addHairline(slide, rightX + 0.7, py + 0.95, 5.5);
    }
  });

  // 右下公司信息
  slide.addText("上海云之脑智能科技有限公司", {
    x: rightX, y: 6.8, w: 6.0, h: 0.3,
    fontFace: FONTS.body,
    fontSize: 10,
    color: COLORS.muted,
  });

  return slide;
}

// ============================================================
// 页面 02 — 项目概览
// ============================================================
function slide02_overview() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "项目概览  /  PROJECT OVERVIEW");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "面向领域知识的 AI 原生学习平台", SPACING.marginX + 0.2, 0.82);

  // 副标题/引语
  slide.addText("融合学情分析、知识图谱、幻觉检测与自适应导学，构建可信赖的智能教育基础设施", {
    x: SPACING.marginX + 0.2, y: 1.55,
    w: SLIDE_W - SPACING.marginX * 2 - 0.2, h: 0.35,
    fontFace: FONTS.body,
    fontSize: 12,
    color: COLORS.muted,
    italic: true,
  });

  addHairline(slide, SPACING.marginX, 2.05, SLIDE_W - SPACING.marginX * 2);

  // 左侧：项目背景与挑战
  const leftX = SPACING.marginX;
  const contentY = 2.25;

  slide.addText("背景与挑战", {
    x: leftX, y: contentY, w: 5.8, h: 0.35,
    fontFace: FONTS.head,
    fontSize: 14,
    color: COLORS.ink,
    bold: true,
  });

  const challenges = [
    { icon: "●", text: "传统学习资源千人一面，无法匹配个体认知差异" },
    { icon: "●", text: "大模型生成内容存在幻觉风险，事实准确性难以保障" },
    { icon: "●", text: "知识零散分布，缺乏结构化组织与语义检索能力" },
    { icon: "●", text: "学习效果难以量化评估，教学闭环不完整" },
  ];

  challenges.forEach((c, i) => {
    const cy = contentY + 0.5 + i * 0.48;
    slide.addText(c.icon, {
      x: leftX, y: cy, w: 0.3, h: 0.38,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.accent,
      valign: "top",
    });
    slide.addText(c.text, {
      x: leftX + 0.3, y: cy, w: 5.5, h: 0.38,
      fontFace: FONTS.body,
      fontSize: 11,
      color: COLORS.ink,
      valign: "top",
      lineSpacing: 1.3,
    });
  });

  // 中间分隔
  addHairline(slide, 6.5, contentY, 0, COLORS.hairline);
  slide.addShape(pptx.ShapeType.line, {
    x: 6.5, y: contentY, w: 0, h: 3.0,
    line: { color: COLORS.hairline, width: 0.75 },
  });

  // 右侧：核心价值
  const rightX = 6.9;

  slide.addText("核心价值主张", {
    x: rightX, y: contentY, w: 5.8, h: 0.35,
    fontFace: FONTS.head,
    fontSize: 14,
    color: COLORS.ink,
    bold: true,
  });

  const values = [
    { num: "1", label: "个性化", desc: "学情画像驱动的千人千面学习路径" },
    { num: "2", label: "可信赖", desc: "多智能体辩论 + 幻觉检测双重质量保障" },
    { num: "3", label: "结构化", desc: "知识图谱 + 向量检索的语义化知识管理" },
    { num: "4", label: "可量化", desc: "学习增益曲线 + 多维指标的效果度量" },
  ];

  values.forEach((v, i) => {
    const vy = contentY + 0.5 + i * 0.68;
    // 圆形序号
    slide.addShape(pptx.ShapeType.ellipse, {
      x: rightX, y: vy + 0.02, w: 0.38, h: 0.38,
      fill: { color: COLORS.accentLight },
      line: { color: COLORS.accentLight, width: 0 },
    });
    addSingleLineToken(slide, v.num, {
      x: rightX, y: vy + 0.02, w: 0.38, h: 0.38,
      fontFace: FONTS.head,
      fontSize: 14,
      bold: true,
      color: COLORS.accent,
      align: "center",
      valign: "middle",
    });
    slide.addText(v.label, {
      x: rightX + 0.55, y: vy, w: 2.0, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 13,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });
    slide.addText(v.desc, {
      x: rightX + 0.55, y: vy + 0.32, w: 5.2, h: 0.3,
      fontFace: FONTS.body,
      fontSize: 10.5,
      color: COLORS.muted,
      valign: "top",
    });
  });

  // 底部：项目定位条
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.8,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.75,
    fill: { color: COLORS.surfaceAlt },
    line: { color: COLORS.hairline, width: 0.75 },
  });

  slide.addText("项目定位", {
    x: SPACING.marginX + 0.3, y: 5.8, w: 1.5, h: 0.75,
    fontFace: FONTS.head,
    fontSize: 11,
    color: COLORS.muted,
    bold: true,
    charSpacing: 1,
    valign: "middle",
  });

  slide.addText(
    "国内领先的 AI 原生领域知识学习平台  ·  以多智能体协同决策为核心，提供从知识管理到个性化导学的全链路解决方案",
    {
      x: SPACING.marginX + 1.8, y: 5.8,
      w: SLIDE_W - SPACING.marginX * 2 - 2.1, h: 0.75,
      fontFace: FONTS.head,
      fontSize: 12.5,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    }
  );

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎项目组  ·  基于 v1.0.0 版本整理");
  addPageNumber(slide, "02");

  return slide;
}

// ============================================================
// 页面 03 — 技术架构
// ============================================================
function slide03_architecture() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "技术架构  /  TECHNICAL ARCHITECTURE");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "全栈现代化架构，支撑从开发到生产的全流程", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：技术栈表格
  const leftX = SPACING.marginX;
  const tableY = 1.85;

  slide.addText("技术栈总览", {
    x: leftX, y: tableY - 0.05, w: 5.5, h: 0.35,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const techStack = [
    { layer: "前端层", tech: "React 18 + TypeScript + Vite", detail: "Tailwind CSS · Zustand · React Router" },
    { layer: "后端层", tech: "FastAPI + SQLAlchemy + Pydantic", detail: "JWT 认证 · 异步 I/O · RESTful" },
    { layer: "数据层", tech: "SQLite / PostgreSQL + Redis", detail: "Alembic 迁移 · Celery 任务队列" },
    { layer: "AI 层", tech: "OpenAI API + ChromaDB", detail: "向量检索 · Sentence-Transformers" },
    { layer: "部署层", tech: "Docker + K8s + Helm", detail: "Nginx 反向代理 · ArgoCD GitOps" },
    { layer: "桌面端", tech: "Electron + .NET Launcher", detail: "Python 运行时打包 · Windows Installer" },
  ];

  techStack.forEach((row, i) => {
    const ry = tableY + 0.4 + i * 0.55;
    // 层标签
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: ry, w: 0.9, h: 0.42,
      fill: { color: COLORS.accentLight },
      line: { color: COLORS.accentLight, width: 0 },
    });
    slide.addText(row.layer, {
      x: leftX, y: ry, w: 0.9, h: 0.42,
      fontFace: FONTS.head,
      fontSize: 10.5,
      color: COLORS.accent,
      bold: true,
      align: "center",
      valign: "middle",
    });
    // 主技术
    slide.addText(row.tech, {
      x: leftX + 1.05, y: ry - 0.02, w: 4.6, h: 0.24,
      fontFace: FONTS.body,
      fontSize: 11,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });
    // 细节
    slide.addText(row.detail, {
      x: leftX + 1.05, y: ry + 0.22, w: 4.6, h: 0.2,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      valign: "middle",
    });
    // 分隔线
    if (i < techStack.length - 1) {
      addHairline(slide, leftX, ry + 0.5, 5.65);
    }
  });

  // 右侧：架构图
  const rightX = 6.8;
  const archY = 1.85;

  slide.addText("系统分层架构", {
    x: rightX, y: archY - 0.05, w: 5.8, h: 0.35,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  // 架构图层级
  const layers = [
    { name: "用户接入层", items: ["Web 前端", "桌面客户端", "API 网关"], color: COLORS.accent },
    { name: "业务服务层", items: ["认证授权", "知识管理", "学习者画像", "智能体协同"], color: "2D7DD2" },
    { name: "AI 能力层", items: ["诊断智能体", "生成智能体", "评判智能体", "编排智能体"], color: COLORS.teal },
    { name: "数据存储层", items: ["关系型数据库", "向量数据库", "缓存队列", "文件存储"], color: "64748B" },
  ];

  layers.forEach((layer, i) => {
    const ly = archY + 0.4 + i * 1.05;
    const lw = 5.9;
    const lh = 0.88;

    // 层背景
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: ly, w: lw, h: lh,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    // 左侧色条
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: ly, w: 0.08, h: lh,
      fill: { color: layer.color },
      line: { color: layer.color, width: 0 },
    });

    // 层名称
    slide.addText(layer.name, {
      x: rightX + 0.25, y: ly, w: 1.5, h: lh,
      fontFace: FONTS.head,
      fontSize: 11,
      color: layer.color,
      bold: true,
      valign: "middle",
    });

    // 模块标签
    const itemW = (lw - 1.8) / layer.items.length - 0.1;
    layer.items.forEach((item, j) => {
      const ix = rightX + 1.8 + j * (itemW + 0.1);
      slide.addShape(pptx.ShapeType.rect, {
        x: ix, y: ly + 0.22, w: itemW, h: 0.44,
        fill: { color: COLORS.surfaceAlt },
        line: { color: COLORS.hairline, width: 0.5 },
      });
      slide.addText(item, {
        x: ix, y: ly + 0.22, w: itemW, h: 0.44,
        fontFace: FONTS.body,
        fontSize: 9.5,
        color: COLORS.ink,
        align: "center",
        valign: "middle",
      });
    });

    // 向下箭头
    if (i < layers.length - 1) {
      slide.addShape(pptx.ShapeType.triangle, {
        x: rightX + lw / 2 - 0.08, y: ly + lh + 0.05,
        w: 0.16, h: 0.1,
        rotate: 180,
        fill: { color: COLORS.hairline },
        line: { color: COLORS.hairline, width: 0 },
      });
    }
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎技术架构文档  ·  v1.0.0");
  addPageNumber(slide, "03");

  return slide;
}

// ============================================================
// 页面 04 — 核心功能模块
// ============================================================
function slide04_coreModules() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "核心功能  /  CORE MODULES");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "六大核心模块，构建完整智能学习闭环", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 2x3 网格布局
  const modules = [
    {
      badge: "智", title: "多智能体协同决策", num: "01",
      desc: "诊断、生成、评判、编排四大智能体，通过多轮辩论优化输出质量",
      features: ["多轮辩论机制", "任务编排调度", "状态实时追踪"],
      color: COLORS.accent,
    },
    {
      badge: "学", title: "学习者画像", num: "02",
      desc: "基于答题记录和行为数据构建多维学情画像",
      features: ["知识掌握度分析", "学习风格识别", "认知水平评估"],
      color: COLORS.teal,
    },
    {
      badge: "知", title: "领域知识库", num: "03",
      desc: "支持文档上传、智能切片、向量索引与语义检索",
      features: ["智能文本切片", "Chroma 向量库", "RAG 检索增强"],
      color: COLORS.purple,
    },
    {
      badge: "生", title: "个性化资源生成", num: "04",
      desc: "根据学情画像动态生成练习题、讲解材料与学习路径",
      features: ["题目自动生成", "讲义智能编写", "学习路径规划"],
      color: COLORS.pink,
    },
    {
      badge: "检", title: "幻觉检测与纠偏", num: "05",
      desc: "自动检测生成内容中的事实性错误并智能纠偏",
      features: ["多维度幻觉检测", "证据溯源验证", "自动修正建议"],
      color: COLORS.caution,
    },
    {
      badge: "量", title: "量化指标监控", num: "06",
      desc: "幻觉率、匹配准确率、知识覆盖率等核心指标可视化",
      features: ["学习增益曲线", "实时指标看板", "报告自动导出"],
      color: COLORS.positive,
    },
  ];

  const startY = 1.85;
  const cardW = (SLIDE_W - SPACING.marginX * 2 - SPACING.panelGap * 2) / 3;
  const cardH = 2.45;

  modules.forEach((m, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const cx = SPACING.marginX + col * (cardW + SPACING.panelGap);
    const cy = startY + row * (cardH + SPACING.panelGap);

    // 卡片背景
    addEvidencePanel(slide, cx, cy, cardW, cardH, { headerColor: m.color });

    // 序号
    addSingleLineToken(slide, m.num, {
      x: cx + 0.25, y: cy + 0.2, w: 0.5, h: 0.35,
      fontFace: FONTS.head,
      fontSize: 14,
      bold: true,
      color: m.color,
      valign: "middle",
    });

    // 标题
    slide.addText(m.title, {
      x: cx + 0.25, y: cy + 0.6, w: cardW - 0.5, h: 0.35,
      fontFace: FONTS.head,
      fontSize: 14,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 描述
    slide.addText(m.desc, {
      x: cx + 0.25, y: cy + 1.0, w: cardW - 0.5, h: 0.6,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
      lineSpacing: 1.4,
    });

    // 分隔线
    addHairline(slide, cx + 0.25, cy + 1.68, cardW - 0.5);

    // 特性标签
    m.features.forEach((f, fi) => {
      const fx = cx + 0.25 + fi * ((cardW - 0.5) / 3);
      const fw = (cardW - 0.5) / 3 - 0.1;
      slide.addShape(pptx.ShapeType.rect, {
        x: fx, y: cy + 1.85, w: fw, h: 0.35,
        fill: { color: COLORS.surfaceAlt },
        line: { color: COLORS.hairline, width: 0.5 },
      });
      slide.addText(f, {
        x: fx, y: cy + 1.85, w: fw, h: 0.35,
        fontFace: FONTS.body,
        fontSize: 8.5,
        color: COLORS.ink,
        align: "center",
        valign: "middle",
      });
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎功能模块说明文档");
  addPageNumber(slide, "04");

  return slide;
}

// ============================================================
// 页面 05 — 多智能体协同
// ============================================================
function slide05_multiAgent() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "智能体系统  /  MULTI-AGENT SYSTEM");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "四智能体协同决策，辩论式质量优化", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 上方：四个智能体横向排列
  const agents = [
    { name: "诊断智能体", role: "Diagnosis Agent", desc: "学情分析与知识缺口诊断", color: COLORS.accent, colorFaint: COLORS.accentFaint, colorSoft: COLORS.accentSoft, badge: "诊" },
    { name: "生成智能体", role: "Generation Agent", desc: "个性化学习资源生成", color: COLORS.teal, colorFaint: COLORS.tealFaint, colorSoft: COLORS.tealSoft, badge: "生" },
    { name: "评判智能体", role: "Judge Agent", desc: "质量审核与幻觉检测", color: COLORS.caution, colorFaint: COLORS.cautionFaint, colorSoft: COLORS.cautionSoft, badge: "评" },
    { name: "编排智能体", role: "Orchestrator", desc: "任务调度与多轮协调", color: COLORS.purple, colorFaint: COLORS.purpleFaint, colorSoft: COLORS.purpleSoft, badge: "编" },
  ];

  const agentY = 1.85;
  const agentW = (SLIDE_W - SPACING.marginX * 2 - SPACING.panelGap * 3) / 4;
  const agentH = 1.8;

  agents.forEach((a, i) => {
    const ax = SPACING.marginX + i * (agentW + SPACING.panelGap);

    // 卡片
    addEvidencePanel(slide, ax, agentY, agentW, agentH, { headerColor: a.color });

    // 图标区域
    slide.addShape(pptx.ShapeType.ellipse, {
      x: ax + agentW / 2 - 0.35, y: agentY + 0.25, w: 0.7, h: 0.7,
      fill: { color: a.color },
      line: { color: a.color, width: 0 },
    });
    slide.addText(a.badge, {
      x: ax + agentW / 2 - 0.35, y: agentY + 0.25, w: 0.7, h: 0.7,
      fontFace: FONTS.head,
      fontSize: 24,
      color: "FFFFFF",
      bold: true,
      align: "center",
      valign: "middle",
    });

    // 名称
    slide.addText(a.name, {
      x: ax, y: agentY + 1.05, w: agentW, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 13,
      color: COLORS.ink,
      bold: true,
      align: "center",
      valign: "middle",
    });

    // 英文角色
    slide.addText(a.role, {
      x: ax, y: agentY + 1.32, w: agentW, h: 0.2,
      fontFace: FONTS.mono,
      fontSize: 8.5,
      color: COLORS.muted,
      align: "center",
      valign: "middle",
    });

    // 描述
    slide.addText(a.desc, {
      x: ax + 0.15, y: agentY + 1.5, w: agentW - 0.3, h: 0.25,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      align: "center",
      valign: "top",
    });
  });

  // 下方：协作流程
  const flowY = 4.0;
  slide.addText("协同决策流程", {
    x: SPACING.marginX, y: flowY, w: 4, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  // 流程步骤
  const steps = [
    { step: "STEP 1", title: "学情诊断", desc: "分析学习者知识掌握度" },
    { step: "STEP 2", title: "资源生成", desc: "生成个性化学习材料" },
    { step: "STEP 3", title: "质量评判", desc: "幻觉检测与质量审核" },
    { step: "STEP 4", title: "迭代优化", desc: "多轮辩论直至达标" },
  ];

  const stepY = flowY + 0.45;
  const stepW = (SLIDE_W - SPACING.marginX * 2 - 1.5) / 4;
  const stepH = 1.1;

  steps.forEach((s, i) => {
    const sx = SPACING.marginX + i * (stepW + 0.5);

    // 步骤号
    addSingleLineToken(slide, s.step, {
      x: sx, y: stepY, w: stepW, h: 0.22,
      fontFace: FONTS.head,
      fontSize: 9,
      bold: true,
      color: COLORS.accent,
      charSpacing: 1,
    });

    // 步骤框
    slide.addShape(pptx.ShapeType.rect, {
      x: sx, y: stepY + 0.28, w: stepW, h: stepH - 0.28,
      fill: { color: COLORS.surfaceAlt },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    slide.addText(s.title, {
      x: sx, y: stepY + 0.35, w: stepW, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      align: "center",
      valign: "middle",
    });

    slide.addText(s.desc, {
      x: sx + 0.1, y: stepY + 0.68, w: stepW - 0.2, h: 0.3,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      align: "center",
      valign: "top",
    });

    // 箭头
    if (i < steps.length - 1) {
      const arrowX = sx + stepW + 0.1;
      slide.addShape(pptx.ShapeType.triangle, {
        x: arrowX, y: stepY + stepH / 2 - 0.04,
        w: 0.15, h: 0.08,
        rotate: 90,
        fill: { color: COLORS.accent },
        line: { color: COLORS.accent, width: 0 },
      });
      slide.addShape(pptx.ShapeType.line, {
        x: arrowX - 0.15, y: stepY + stepH / 2,
        w: 0.3, h: 0,
        line: { color: COLORS.accent, width: 1.5 },
      });
    }
  });

  // 底部关键指标条
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.9,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.65,
    fill: { color: COLORS.ink },
    line: { color: COLORS.ink, width: 0 },
  });

  const metrics = [
    { value: "4", label: "智能体数量" },
    { value: "N", label: "辩论轮次" },
    { value: "<5%", label: "目标幻觉率" },
    { value: "SSE", label: "实时反馈" },
  ];

  metrics.forEach((m, i) => {
    const mx = SPACING.marginX + i * ((SLIDE_W - SPACING.marginX * 2) / 4);
    const mw = (SLIDE_W - SPACING.marginX * 2) / 4;
    addSingleLineToken(slide, m.value, {
      x: mx, y: 5.95, w: mw, h: 0.32,
      fontFace: FONTS.head,
      fontSize: 18,
      bold: true,
      color: "FFFFFF",
      align: "center",
      valign: "middle",
    });
    slide.addText(m.label, {
      x: mx, y: 6.28, w: mw, h: 0.22,
      fontFace: FONTS.body,
      fontSize: 9,
      color: "94A3B8",
      align: "center",
      valign: "middle",
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎多智能体架构设计文档");
  addPageNumber(slide, "05");

  return slide;
}

// ============================================================
// 页面 06 — 技术亮点 I：知识图谱与 RAG
// ============================================================
function slide06_rag() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "技术亮点  /  TECHNOLOGY HIGHLIGHTS  ·  Ⅰ");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "知识图谱 + RAG 检索增强，精准召回领域知识", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：RAG 流程图
  const leftX = SPACING.marginX;
  const flowY = 1.85;

  slide.addText("RAG 检索增强生成流程", {
    x: leftX, y: flowY - 0.05, w: 6, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const ragSteps = [
    { title: "知识摄入", desc: "文档上传 · 格式解析", color: COLORS.accent },
    { title: "智能切片", desc: "语义分块 · 元数据标注", color: "2D7DD2" },
    { title: "向量化索引", desc: "Embedding · Chroma 存储", color: COLORS.teal },
    { title: "语义检索", desc: "相似度匹配 · 重排序", color: "7C3AED" },
    { title: "增强生成", desc: "上下文注入 · 精准回答", color: COLORS.caution },
  ];

  ragSteps.forEach((s, i) => {
    const sy = flowY + 0.35 + i * 0.78;
    // 圆形节点
    slide.addShape(pptx.ShapeType.ellipse, {
      x: leftX + 0.1, y: sy + 0.02, w: 0.42, h: 0.42,
      fill: { color: s.color },
      line: { color: s.color, width: 0 },
    });
    addSingleLineToken(slide, `${i + 1}`, {
      x: leftX + 0.1, y: sy + 0.02, w: 0.42, h: 0.42,
      fontFace: FONTS.head,
      fontSize: 14,
      bold: true,
      color: "FFFFFF",
      align: "center",
      valign: "middle",
    });
    // 标题
    slide.addText(s.title, {
      x: leftX + 0.7, y: sy, w: 2.5, h: 0.26,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });
    // 描述
    slide.addText(s.desc, {
      x: leftX + 0.7, y: sy + 0.26, w: 2.5, h: 0.2,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
    });
    // 竖线连接
    if (i < ragSteps.length - 1) {
      slide.addShape(pptx.ShapeType.line, {
        x: leftX + 0.31, y: sy + 0.44,
        w: 0, h: 0.34,
        line: { color: COLORS.hairline, width: 1.5, dashType: "dash" },
      });
    }
  });

  // 右侧：知识库能力
  const rightX = 6.8;
  const capY = 1.85;

  slide.addText("知识库核心能力", {
    x: rightX, y: capY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const capabilities = [
    { label: "支持文档格式", value: "Markdown / TXT / PDF / DOCX", badge: "文" },
    { label: "向量数据库", value: "ChromaDB + HNSW 索引", badge: "库" },
    { label: "Embedding 模型", value: "Sentence-Transformers", badge: "向" },
    { label: "知识切片策略", value: "语义分块 + 重叠窗口", badge: "切" },
    { label: "检索方式", value: "向量检索 + 关键词混合", badge: "检" },
    { label: "知识领域覆盖", value: "AI / 数学 / 电气 / 工控 等", badge: "域" },
  ];

  capabilities.forEach((c, i) => {
    const cy = capY + 0.35 + i * 0.58;
    const cw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: cy, w: cw, h: 0.48,
      fill: { color: i % 2 === 0 ? COLORS.surface : COLORS.surfaceAlt },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    addTextBadge(slide, rightX + 0.13, cy + 0.06, 0.36, c.badge, COLORS.teal);

    slide.addText(c.label, {
      x: rightX + 0.6, y: cy, w: 2.0, h: 0.48,
      fontFace: FONTS.body,
      fontSize: 10.5,
      color: COLORS.muted,
      valign: "middle",
    });

    slide.addText(c.value, {
      x: rightX + 2.6, y: cy, w: cw - 2.8, h: 0.48,
      fontFace: FONTS.head,
      fontSize: 10.5,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });
  });

  // 底部种子知识统计
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 6.0,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.55,
    fill: { color: COLORS.accentLight },
    line: { color: COLORS.accentSoft, width: 0.75 },
  });

  const stats = [
    { value: "60+", label: "内置种子知识文档" },
    { value: "8 大类", label: "学科领域覆盖" },
    { value: "毫秒级", label: "向量检索响应" },
    { value: "95%+", label: "检索准确率" },
  ];

  stats.forEach((s, i) => {
    const sx = SPACING.marginX + i * ((SLIDE_W - SPACING.marginX * 2) / 4);
    const sw = (SLIDE_W - SPACING.marginX * 2) / 4;
    addSingleLineToken(slide, s.value, {
      x: sx, y: 6.02, w: sw, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 16,
      bold: true,
      color: COLORS.accent,
      align: "center",
      valign: "middle",
    });
    slide.addText(s.label, {
      x: sx, y: 6.32, w: sw, h: 0.2,
      fontFace: FONTS.body,
      fontSize: 9,
      color: COLORS.muted,
      align: "center",
      valign: "middle",
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎知识库技术方案  ·  ChromaDB + Sentence-Transformers");
  addPageNumber(slide, "06");

  return slide;
}

// ============================================================
// 页面 07 — 技术亮点 II：幻觉检测
// ============================================================
function slide07_hallucination() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "技术亮点  /  TECHNOLOGY HIGHLIGHTS  ·  Ⅱ");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "多维度幻觉检测体系，保障生成内容可信度", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：检测维度
  const leftX = SPACING.marginX;
  const dimY = 1.85;

  slide.addText("幻觉检测维度", {
    x: leftX, y: dimY - 0.05, w: 5.5, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const dimensions = [
    { name: "事实一致性", desc: "验证生成内容与知识库事实的匹配度", level: "高", color: COLORS.risk, colorFaint: COLORS.riskFaint, colorSoft: COLORS.riskSoft },
    { name: "来源可追溯性", desc: "每个论断都能溯源到具体知识片段", level: "高", color: COLORS.caution, colorFaint: COLORS.cautionFaint, colorSoft: COLORS.cautionSoft },
    { name: "逻辑自洽性", desc: "检测内容内部的逻辑矛盾与冲突", level: "中", color: COLORS.positive, colorFaint: COLORS.positiveFaint, colorSoft: COLORS.positiveSoft },
    { name: "数值准确性", desc: "校验数字、公式、统计数据的正确性", level: "高", color: COLORS.risk, colorFaint: COLORS.riskFaint, colorSoft: COLORS.riskSoft },
    { name: "概念准确性", desc: "确保专业术语和概念定义准确无误", level: "中", color: COLORS.caution, colorFaint: COLORS.cautionFaint, colorSoft: COLORS.cautionSoft },
  ];

  dimensions.forEach((d, i) => {
    const dy = dimY + 0.35 + i * 0.62;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: dy, w: 5.65, h: 0.52,
      fill: { color: i % 2 === 0 ? COLORS.surface : COLORS.surfaceAlt },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    // 名称
    slide.addText(d.name, {
      x: leftX + 0.2, y: dy, w: 1.6, h: 0.52,
      fontFace: FONTS.head,
      fontSize: 11,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 描述
    slide.addText(d.desc, {
      x: leftX + 1.9, y: dy, w: 2.8, h: 0.52,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      valign: "middle",
    });

    // 风险等级标签
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX + 4.85, y: dy + 0.12, w: 0.65, h: 0.28,
      fill: { color: d.colorFaint },
      line: { color: d.colorSoft, width: 0.5 },
    });
    slide.addText(d.level + "风险", {
      x: leftX + 4.85, y: dy + 0.12, w: 0.65, h: 0.28,
      fontFace: FONTS.head,
      fontSize: 8.5,
      color: d.color,
      bold: true,
      align: "center",
      valign: "middle",
    });
  });

  // 右侧：质量保障机制
  const rightX = 6.8;
  const qaY = 1.85;

  slide.addText("质量保障机制", {
    x: rightX, y: qaY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const mechanisms = [
    {
      title: "多轮辩论优化",
      desc: "生成与评判智能体多轮交互，逐步提升内容质量",
      badge: "辩",
    },
    {
      title: "证据溯源验证",
      desc: "生成内容自动关联知识库来源，支持一键溯源",
      badge: "溯",
    },
    {
      title: "人工审核通道",
      desc: "高风险内容支持专家标注与审核，持续优化模型",
      badge: "审",
    },
    {
      title: "指标量化监控",
      desc: "幻觉率、匹配率、覆盖率等核心指标实时监控",
      badge: "量",
    },
  ];

  mechanisms.forEach((m, i) => {
    const my = qaY + 0.35 + i * 0.85;
    const mw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: my, w: mw, h: 0.72,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    // 左侧色条
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: my, w: 0.06, h: 0.72,
      fill: { color: COLORS.teal },
      line: { color: COLORS.teal, width: 0 },
    });

    addTextBadge(slide, rightX + 0.22, my + 0.16, 0.42, m.badge, COLORS.teal);

    slide.addText(m.title, {
      x: rightX + 0.8, y: my + 0.08, w: mw - 1.0, h: 0.28,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(m.desc, {
      x: rightX + 0.8, y: my + 0.36, w: mw - 1.0, h: 0.3,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
      lineSpacing: 1.3,
    });
  });

  // 底部：幻觉检测指标条
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.95,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.6,
    fill: { color: COLORS.amberFaint },
    line: { color: COLORS.amberSoft, width: 0.75 },
  });

  slide.addText("质量承诺", {
    x: SPACING.marginX + 0.3, y: 5.95, w: 2, h: 0.6,
    fontFace: FONTS.head,
    fontSize: 12,
    color: "92400E",
    bold: true,
    valign: "middle",
  });

  slide.addText(
    "通过多智能体辩论 + 证据溯源 + 人工审核三重保障，将生成内容幻觉率控制在 5% 以下",
    {
      x: SPACING.marginX + 2.3, y: 5.95,
      w: SLIDE_W - SPACING.marginX * 2 - 2.6, h: 0.6,
      fontFace: FONTS.body,
      fontSize: 11,
      color: "78350F",
      valign: "middle",
    }
  );

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎幻觉检测技术方案  ·  基于评判智能体与证据溯源机制");
  addPageNumber(slide, "07");

  return slide;
}

// ============================================================
// 页面 08 — 部署方案
// ============================================================
function slide08_deployment() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "桌面交付  /  DESKTOP DELIVERY");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "Windows 桌面版 — 开箱即用，零配置体验", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：核心特性
  const leftX = SPACING.marginX;
  const featY = 1.85;

  slide.addText("核心特性", {
    x: leftX, y: featY - 0.05, w: 6, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const features = [
    { badge: "01", title: "一键安装启动", desc: "标准 Windows Installer，双击即装即用，无需配置开发环境" },
    { badge: "02", title: "完整 AI 运行时", desc: "内置 Python 与 ChromaDB，本地向量检索开箱可用" },
    { badge: "03", title: "自动端口管理", desc: "后端自动选择可用端口，关闭程序时自动清理后台服务" },
    { badge: "04", title: "用户数据独立", desc: "数据库、日志、知识文件存入用户目录，不污染安装目录" },
    { badge: "05", title: "AI 配置中心", desc: "按用户隔离的模型配置，支持多服务商接入，密钥加密存储" },
    { badge: "06", title: "约 575MB 安装包", desc: "完整功能打包，体积主要来自本地向量库与科学计算运行时" },
  ];

  features.forEach((f, i) => {
    const fy = featY + 0.35 + i * 0.65;
    const fw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: fy, w: fw, h: 0.55,
      fill: { color: i % 2 === 0 ? COLORS.surface : COLORS.surfaceAlt },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    // 左侧色条
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: fy, w: 0.06, h: 0.55,
      fill: { color: COLORS.purple },
      line: { color: COLORS.purple, width: 0 },
    });

    // 序号徽章
    addTextBadge(slide, leftX + 0.18, fy + 0.07, 0.42, f.badge, COLORS.purple);

    slide.addText(f.title, {
      x: leftX + 0.75, y: fy, w: 2.0, h: 0.55,
      fontFace: FONTS.head,
      fontSize: 11.5,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(f.desc, {
      x: leftX + 2.8, y: fy, w: fw - 3.0, h: 0.55,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "middle",
      lineSpacing: 1.3,
    });
  });

  // 右侧：安装与使用流程
  const rightX = 6.8;
  const flowY = 1.85;

  slide.addText("安装与使用流程", {
    x: rightX, y: flowY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const steps = [
    { num: "01", title: "下载安装包", desc: "获取 ZhiyuEngine-Setup.exe" },
    { num: "02", title: "运行安装向导", desc: "选择路径，创建桌面快捷方式" },
    { num: "03", title: "首次启动配置", desc: "创建本地管理员账号" },
    { num: "04", title: "AI 模型配置", desc: "接入个人模型服务或跳过体验" },
    { num: "05", title: "开始使用", desc: "导入知识、创建学习者、生成资源" },
  ];

  steps.forEach((s, i) => {
    const sy = flowY + 0.4 + i * 0.78;
    const sw = 5.9;

    // 序号圆形
    slide.addShape(pptx.ShapeType.ellipse, {
      x: rightX + 0.1, y: sy + 0.08, w: 0.42, h: 0.42,
      fill: { color: COLORS.purple },
      line: { color: COLORS.purple, width: 0 },
    });
    addSingleLineToken(slide, s.num, {
      x: rightX + 0.1, y: sy + 0.08, w: 0.42, h: 0.42,
      fontFace: FONTS.head,
      fontSize: 12,
      bold: true,
      color: "FFFFFF",
      align: "center",
      valign: "middle",
    });

    // 内容卡片
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX + 0.7, y: sy, w: sw - 0.8, h: 0.58,
      fill: { color: COLORS.purpleFaint },
      line: { color: COLORS.purpleSoft, width: 0.5 },
    });

    slide.addText(s.title, {
      x: rightX + 0.9, y: sy + 0.04, w: sw - 1.2, h: 0.28,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(s.desc, {
      x: rightX + 0.9, y: sy + 0.32, w: sw - 1.2, h: 0.22,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
    });

    // 连接线
    if (i < steps.length - 1) {
      slide.addShape(pptx.ShapeType.line, {
        x: rightX + 0.31, y: sy + 0.5,
        w: 0, h: 0.28,
        line: { color: COLORS.purpleSoft, width: 1.5, dashType: "dash" },
      });
    }
  });

  // 底部：系统要求条
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.95,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.6,
    fill: { color: COLORS.surfaceAlt },
    line: { color: COLORS.hairline, width: 0.75 },
  });

  slide.addText("系统要求", {
    x: SPACING.marginX + 0.3, y: 5.95, w: 2, h: 0.6,
    fontFace: FONTS.head,
    fontSize: 11,
    color: COLORS.ink,
    bold: true,
    valign: "middle",
  });

  const reqs = [
    "Windows 10/11  64 位",
    "8GB+ 内存",
    "2GB 可用磁盘空间",
    "可选：互联网连接（使用云端模型）",
  ];

  reqs.forEach((r, i) => {
    const rx = SPACING.marginX + 2.3 + i * 2.7;
    slide.addText(r, {
      x: rx, y: 5.95, w: 2.6, h: 0.6,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "middle",
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎 v1.0.0 桌面版发布说明");
  addPageNumber(slide, "08");

  return slide;
}

// ============================================================
// 页面 09 — 质量与运维
// ============================================================
function slide09_quality() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "工程质量  /  ENGINEERING QUALITY");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "完善的质量保障与运维体系", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：测试体系
  const leftX = SPACING.marginX;
  const testY = 1.85;

  slide.addText("测试覆盖体系", {
    x: leftX, y: testY - 0.05, w: 6, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const testLayers = [
    { name: "单元测试", desc: "前后端核心逻辑单元测试", count: "80+", color: COLORS.accent },
    { name: "集成测试", desc: "API 路由与服务层集成测试", count: "40+", color: COLORS.teal },
    { name: "E2E 测试", desc: "Playwright 端到端功能测试", count: "10+", color: "7C3AED" },
    { name: "性能测试", desc: "压力 / 负载 / 尖峰性能测试", count: "4 类", color: COLORS.caution },
  ];

  testLayers.forEach((t, i) => {
    const ty = testY + 0.35 + i * 0.7;
    const tw = 5.8;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: ty, w: tw, h: 0.58,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    // 左侧色条
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: ty, w: 0.06, h: 0.58,
      fill: { color: t.color },
      line: { color: t.color, width: 0 },
    });

    // 名称
    slide.addText(t.name, {
      x: leftX + 0.25, y: ty, w: 1.5, h: 0.58,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 描述
    slide.addText(t.desc, {
      x: leftX + 1.8, y: ty, w: 2.8, h: 0.58,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "middle",
    });

    // 数量
    addSingleLineToken(slide, t.count, {
      x: leftX + 4.8, y: ty, w: 0.9, h: 0.58,
      fontFace: FONTS.head,
      fontSize: 16,
      bold: true,
      color: t.color,
      align: "right",
      valign: "middle",
    });
  });

  // 右侧：运维能力
  const rightX = 6.8;
  const opsY = 1.85;

  slide.addText("生产级运维能力", {
    x: rightX, y: opsY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const opsCapabilities = [
    { badge: "监", title: "监控告警", desc: "Prometheus + Grafana + 10 条告警规则" },
    { badge: "备", title: "备份恢复", desc: "PostgreSQL 每日备份 + Velero PVC 快照" },
    { badge: "发", title: "发布策略", desc: "蓝绿部署 · 金丝雀发布 · 秒级回滚" },
    { badge: "安", title: "安全合规", desc: "数据脱敏 · JWT 认证 · 权限边界" },
    { badge: "志", title: "日志审计", desc: "结构化日志 · 操作审计 · 问题追踪" },
  ];

  opsCapabilities.forEach((o, i) => {
    const oy = opsY + 0.35 + i * 0.58;
    const ow = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: oy, w: ow, h: 0.48,
      fill: { color: i % 2 === 0 ? COLORS.surfaceAlt : COLORS.surface },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    addTextBadge(slide, rightX + 0.13, oy + 0.06, 0.36, o.badge, COLORS.accent);

    slide.addText(o.title, {
      x: rightX + 0.65, y: oy, w: 1.5, h: 0.48,
      fontFace: FONTS.head,
      fontSize: 11,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(o.desc, {
      x: rightX + 2.2, y: oy, w: ow - 2.4, h: 0.48,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "middle",
    });
  });

  // 底部：CI/CD 流水线
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.9,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.65,
    fill: { color: COLORS.surfaceAlt },
    line: { color: COLORS.hairline, width: 0.75 },
  });

  slide.addText("CI/CD 流水线", {
    x: SPACING.marginX + 0.3, y: 5.9, w: 2, h: 0.65,
    fontFace: FONTS.head,
    fontSize: 11,
    color: COLORS.muted,
    bold: true,
    valign: "middle",
  });

  const pipeline = [
    "代码提交",
    "Lint + Type Check",
    "单元测试",
    "集成测试",
    "构建镜像",
    "部署发布",
  ];

  pipeline.forEach((p, i) => {
    const px = SPACING.marginX + 2.3 + i * 1.45;
    const pw = 1.3;

    if (i > 0) {
      // 箭头
      slide.addShape(pptx.ShapeType.line, {
        x: px - 0.18, y: 6.22,
        w: 0.12, h: 0,
        line: { color: COLORS.accent, width: 1.5 },
      });
      slide.addShape(pptx.ShapeType.triangle, {
        x: px - 0.06, y: 6.18,
        w: 0.08, h: 0.08,
        rotate: 90,
        fill: { color: COLORS.accent },
        line: { color: COLORS.accent, width: 0 },
      });
    }

    slide.addText(p, {
      x: px, y: 6.05, w: pw, h: 0.35,
      fontFace: FONTS.body,
      fontSize: 9,
      color: COLORS.ink,
      align: "center",
      valign: "middle",
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎质量保障与运维体系文档");
  addPageNumber(slide, "09");

  return slide;
}

// ============================================================
// 页面 10 — 学习者画像与自适应导学
// ============================================================
function slide10_learnerProfile() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "学习者画像  /  LEARNER PROFILE");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "多维学情画像，驱动个性化自适应导学", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：画像维度
  const leftX = SPACING.marginX;
  const dimY = 1.85;

  slide.addText("学习者画像维度", {
    x: leftX, y: dimY - 0.05, w: 5.5, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const dimensions = [
    { name: "知识掌握度", desc: "各知识点掌握情况、薄弱环节识别", level: "量化", color: COLORS.accent },
    { name: "学习风格", desc: "视觉型 / 听觉型 / 动手型偏好分析", level: "分类", color: COLORS.teal },
    { name: "认知水平", desc: "记忆 / 理解 / 应用 / 分析 / 评价层级", level: "分级", color: COLORS.purple },
    { name: "学习进度", desc: "学习时长、完成率、学习曲线分析", level: "时序", color: COLORS.caution },
    { name: "能力模型", desc: "综合能力评估与发展建议", level: "综合", color: COLORS.positive },
  ];

  dimensions.forEach((d, i) => {
    const dy = dimY + 0.35 + i * 0.68;
    const dw = 5.8;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: dy, w: dw, h: 0.58,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    // 左侧色条
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: dy, w: 0.06, h: 0.58,
      fill: { color: d.color },
      line: { color: d.color, width: 0 },
    });

    // 名称
    slide.addText(d.name, {
      x: leftX + 0.25, y: dy, w: 1.6, h: 0.58,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 描述
    slide.addText(d.desc, {
      x: leftX + 1.9, y: dy, w: 2.8, h: 0.58,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "middle",
    });

    // 标签
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX + 4.8, y: dy + 0.15, w: 0.85, h: 0.28,
      fill: { color: d.color + "" },
      line: { color: d.color, width: 0.75 },
    });
    slide.addText(d.level, {
      x: leftX + 4.8, y: dy + 0.15, w: 0.85, h: 0.28,
      fontFace: FONTS.head,
      fontSize: 9,
      color: d.color,
      bold: true,
      align: "center",
      valign: "middle",
    });
  });

  // 右侧：自适应导学机制
  const rightX = 6.8;
  const adaptY = 1.85;

  slide.addText("自适应导学机制", {
    x: rightX, y: adaptY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const adaptSteps = [
    { num: "①", title: "学情诊断", desc: "通过测评与答题记录，建立初始学习者画像" },
    { num: "②", title: "路径规划", desc: "基于画像自动生成个性化学习路径与资源推荐" },
    { num: "③", title: "动态调整", desc: "实时追踪学习效果，动态调整难度与内容" },
    { num: "④", title: "效果反馈", desc: "学习增益曲线可视化，量化展示进步与差距" },
  ];

  adaptSteps.forEach((s, i) => {
    const sy = adaptY + 0.35 + i * 0.95;
    const sw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: sy, w: sw, h: 0.82,
      fill: { color: i % 2 === 0 ? COLORS.surfaceAlt : COLORS.surface },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    addSingleLineToken(slide, s.num, {
      x: rightX + 0.2, y: sy + 0.18, w: 0.5, h: 0.45,
      fontFace: FONTS.head,
      fontSize: 20,
      bold: true,
      color: COLORS.accent,
      valign: "middle",
    });

    slide.addText(s.title, {
      x: rightX + 0.85, y: sy + 0.1, w: sw - 1.0, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(s.desc, {
      x: rightX + 0.85, y: sy + 0.4, w: sw - 1.0, h: 0.35,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
      lineSpacing: 1.3,
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎学习者画像与自适应导学子系统设计");
  addPageNumber(slide, "10");

  return slide;
}

// ============================================================
// 页面 11 — 应用场景与行业覆盖
// ============================================================
function slide11_scenarios() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "应用场景  /  APPLICATION SCENARIOS");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "覆盖多行业领域的知识学习与培训场景", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 2x3 场景网格
  const scenarios = [
    { badge: "工", title: "智能制造培训", desc: "工业自动化、数字孪生、设备运维等专业知识培训", field: "工业制造", color: COLORS.accent },
    { badge: "IT", title: "IT 技术教育", desc: "AI、编程、网络安全、数据库等技术栈体系化学习", field: "信息技术", color: COLORS.teal },
    { badge: "电", title: "电力电气培训", desc: "电力系统、自动化控制、电路理论等专业内容学习", field: "电力电气", color: COLORS.caution },
    { badge: "教", title: "高等教育辅助", desc: "数学、物理、计算机等学科的个性化辅导与练习", field: "高等教育", color: COLORS.purple },
    { badge: "企", title: "企业内训", desc: "新员工入职培训、岗位技能提升、知识库建设", field: "企业培训", color: COLORS.positive },
    { badge: "证", title: "职业认证备考", desc: "职业资格认证、技能等级考试的针对性备考训练", field: "职业认证", color: COLORS.pink },
  ];

  const startY = 1.85;
  const cardW = (SLIDE_W - SPACING.marginX * 2 - SPACING.panelGap * 2) / 3;
  const cardH = 2.2;

  scenarios.forEach((s, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const cx = SPACING.marginX + col * (cardW + SPACING.panelGap);
    const cy = startY + row * (cardH + SPACING.panelGap);

    addEvidencePanel(slide, cx, cy, cardW, cardH, { headerColor: s.color });

    // 行业标签
    slide.addShape(pptx.ShapeType.rect, {
      x: cx + cardW - 1.4, y: cy + 0.2, w: 1.15, h: 0.26,
      fill: { color: s.color + "" },
      line: { color: s.color, width: 0.5 },
    });
    slide.addText(s.field, {
      x: cx + cardW - 1.4, y: cy + 0.2, w: 1.15, h: 0.26,
      fontFace: FONTS.head,
      fontSize: 8.5,
      color: s.color,
      bold: true,
      align: "center",
      valign: "middle",
    });

    // 图标徽章
    addTextBadge(slide, cx + 0.25, cy + 0.35, 0.55, s.badge, s.color);

    // 标题
    slide.addText(s.title, {
      x: cx + 0.25, y: cy + 1.1, w: cardW - 0.5, h: 0.35,
      fontFace: FONTS.head,
      fontSize: 14,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 描述
    slide.addText(s.desc, {
      x: cx + 0.25, y: cy + 1.48, w: cardW - 0.5, h: 0.55,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
      lineSpacing: 1.4,
    });
  });

  // 底部：内置学科覆盖
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 6.5,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.45,
    fill: { color: COLORS.accentLight },
    line: { color: COLORS.accentSoft, width: 0.75 },
  });

  slide.addText("内置种子知识覆盖", {
    x: SPACING.marginX + 0.3, y: 6.5, w: 2.2, h: 0.45,
    fontFace: FONTS.head,
    fontSize: 10.5,
    color: COLORS.accent,
    bold: true,
    valign: "middle",
  });

  const subjects = [
    "人工智能",
    "计算机科学",
    "数学",
    "物理",
    "电力电气",
    "工业物联网",
    "智能制造",
    "网络安全",
    "通用素养",
  ];

  subjects.forEach((subj, i) => {
    const sx = SPACING.marginX + 2.6 + i * 1.15;
    slide.addText(subj, {
      x: sx, y: 6.5, w: 1.1, h: 0.45,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.ink,
      align: "center",
      valign: "middle",
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎知识库种子内容统计");
  addPageNumber(slide, "11");

  return slide;
}

// ============================================================
// 页面 12 — 数据隐私与安全合规
// ============================================================
function slide12_privacy() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "安全合规  /  SECURITY & PRIVACY");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "全方位数据安全与隐私保护机制", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：数据脱敏能力
  const leftX = SPACING.marginX;
  const privY = 1.85;

  slide.addText("内置数据脱敏", {
    x: leftX, y: privY - 0.05, w: 6, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const desens = [
    { type: "姓名脱敏", example: "张三 → *三", method: "姓氏替换", status: "已支持" },
    { type: "手机号脱敏", example: "138****1234", method: "中间掩码", status: "已支持" },
    { type: "身份证号", example: "310***********1234", method: "分段掩码", status: "已支持" },
    { type: "地址脱敏", example: "上海市浦***", method: "区域截断", status: "已支持" },
    { type: "邮箱脱敏", example: "u***@example.com", method: "用户名掩码", status: "已支持" },
  ];

  desens.forEach((d, i) => {
    const dy = privY + 0.35 + i * 0.58;
    const dw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: dy, w: dw, h: 0.48,
      fill: { color: i % 2 === 0 ? COLORS.surface : COLORS.surfaceAlt },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    slide.addText(d.type, {
      x: leftX + 0.2, y: dy, w: 1.4, h: 0.48,
      fontFace: FONTS.head,
      fontSize: 10.5,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(d.example, {
      x: leftX + 1.7, y: dy, w: 1.8, h: 0.48,
      fontFace: FONTS.mono,
      fontSize: 9.5,
      color: COLORS.muted,
      valign: "middle",
    });

    slide.addText(d.method, {
      x: leftX + 3.6, y: dy, w: 1.2, h: 0.48,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      valign: "middle",
    });

    // 状态标签
    slide.addShape(pptx.ShapeType.rect, {
      x: leftX + 4.95, y: dy + 0.12, w: 0.75, h: 0.24,
      fill: { color: COLORS.positiveFaint },
      line: { color: COLORS.positive, width: 0.5 },
    });
    slide.addText(d.status, {
      x: leftX + 4.95, y: dy + 0.12, w: 0.75, h: 0.24,
      fontFace: FONTS.head,
      fontSize: 8.5,
      color: COLORS.positive,
      bold: true,
      align: "center",
      valign: "middle",
    });
  });

  // 右侧：安全保障
  const rightX = 6.8;
  const secY = 1.85;

  slide.addText("安全保障体系", {
    x: rightX, y: secY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const securities = [
    { badge: "认", title: "认证授权", desc: "JWT Token 认证 · 角色权限控制 · 多用户隔离" },
    { badge: "密", title: "密钥加密", desc: "API Key 加密存储 · 日志脱敏 · 配置安全" },
    { badge: "隔", title: "数据隔离", desc: "学习者数据权限边界 · 按账号隔离业务数据" },
    { badge: "审", title: "操作审计", desc: "关键操作日志记录 · 可追溯的变更历史" },
    { badge: "本", title: "本地优先", desc: "桌面版数据本地存储 · 可选完全离线使用" },
  ];

  securities.forEach((s, i) => {
    const sy = secY + 0.35 + i * 0.66;
    const sw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: sy, w: sw, h: 0.56,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: sy, w: 0.06, h: 0.56,
      fill: { color: COLORS.teal },
      line: { color: COLORS.teal, width: 0 },
    });

    addTextBadge(slide, rightX + 0.22, sy + 0.08, 0.4, s.badge, COLORS.teal);

    slide.addText(s.title, {
      x: rightX + 0.75, y: sy, w: 1.5, h: 0.56,
      fontFace: FONTS.head,
      fontSize: 11,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(s.desc, {
      x: rightX + 2.3, y: sy, w: sw - 2.5, h: 0.56,
      fontFace: FONTS.body,
      fontSize: 9.5,
      color: COLORS.muted,
      valign: "middle",
      lineSpacing: 1.3,
    });
  });

  // 底部：隐私承诺条
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 5.9,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.65,
    fill: { color: "ECFDF5" },
    line: { color: COLORS.positiveSoft, width: 0.75 },
  });

  slide.addText("隐私承诺", {
    x: SPACING.marginX + 0.3, y: 5.9, w: 2, h: 0.65,
    fontFace: FONTS.head,
    fontSize: 12,
    color: COLORS.positive,
    bold: true,
    valign: "middle",
  });

  slide.addText(
    "桌面版所有用户数据默认存储在本地，不上传云端；使用云端模型时仅发送必要的生成请求，不存储个人学习数据",
    {
      x: SPACING.marginX + 2.3, y: 5.9,
      w: SLIDE_W - SPACING.marginX * 2 - 2.6, h: 0.65,
      fontFace: FONTS.body,
      fontSize: 10.5,
      color: "065F46",
      valign: "middle",
      lineSpacing: 1.3,
    }
  );

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎数据安全与隐私保护设计文档");
  addPageNumber(slide, "12");

  return slide;
}

// ============================================================
// 页面 13 — 培训与认证体系
// ============================================================
function slide13_training() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "培训认证  /  TRAINING & CERTIFICATION");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "完整的培训管理与认证考核体系", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 左侧：培训管理
  const leftX = SPACING.marginX;
  const trainY = 1.85;

  slide.addText("培训管理功能", {
    x: leftX, y: trainY - 0.05, w: 6, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const trainFeatures = [
    { badge: "计", title: "培训计划管理", desc: "创建培训项目、设定学习目标、安排学习进度" },
    { badge: "学", title: "学员管理", desc: "批量导入学员、分组管理、学习进度追踪" },
    { badge: "题", title: "题库管理", desc: "多题型支持、批量导入、难度分级、知识点标签" },
    { badge: "析", title: "成绩分析", desc: "成绩统计、错题分析、知识点掌握度可视化" },
    { badge: "证", title: "证书颁发", desc: "自动生成培训证书、成绩证明、学习时长证明" },
  ];

  trainFeatures.forEach((t, i) => {
    const ty = trainY + 0.35 + i * 0.78;
    const tw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: ty, w: tw, h: 0.68,
      fill: { color: i % 2 === 0 ? COLORS.surfaceAlt : COLORS.surface },
      line: { color: COLORS.hairline, width: 0.5 },
    });

    slide.addShape(pptx.ShapeType.rect, {
      x: leftX, y: ty, w: 0.06, h: 0.68,
      fill: { color: COLORS.accent },
      line: { color: COLORS.accent, width: 0 },
    });

    addTextBadge(slide, leftX + 0.22, ty + 0.14, 0.42, t.badge, COLORS.accent);

    slide.addText(t.title, {
      x: leftX + 0.8, y: ty + 0.06, w: 2.0, h: 0.3,
      fontFace: FONTS.head,
      fontSize: 11.5,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    slide.addText(t.desc, {
      x: leftX + 0.8, y: ty + 0.36, w: tw - 1.0, h: 0.28,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
    });
  });

  // 右侧：认证体系
  const rightX = 6.8;
  const certY = 1.85;

  slide.addText("认证考核体系", {
    x: rightX, y: certY - 0.05, w: 5.8, h: 0.3,
    fontFace: FONTS.head,
    fontSize: 13,
    color: COLORS.ink,
    bold: true,
  });

  const certLevels = [
    { level: "初级", name: "助理工程师", color: COLORS.positive, req: "掌握基础知识，通过入门考核" },
    { level: "中级", name: "工程师", color: COLORS.accent, req: "具备实操能力，完成项目实践" },
    { level: "高级", name: "高级工程师", color: COLORS.purple, req: "深入理解原理，通过综合评估" },
    { level: "专家", name: "技术专家", color: COLORS.caution, req: "丰富实战经验，答辩评审通过" },
  ];

  certLevels.forEach((c, i) => {
    const cy = certY + 0.35 + i * 0.88;
    const cw = 5.9;

    slide.addShape(pptx.ShapeType.rect, {
      x: rightX, y: cy, w: cw, h: 0.78,
      fill: { color: COLORS.surface },
      line: { color: COLORS.hairline, width: 0.75 },
    });

    // 等级徽章
    slide.addShape(pptx.ShapeType.ellipse, {
      x: rightX + 0.25, y: cy + 0.14, w: 0.52, h: 0.52,
      fill: { color: c.color },
      line: { color: c.color, width: 0 },
    });
    addSingleLineToken(slide, c.level, {
      x: rightX + 0.25, y: cy + 0.14, w: 0.52, h: 0.52,
      fontFace: FONTS.head,
      fontSize: 11,
      bold: true,
      color: "FFFFFF",
      align: "center",
      valign: "middle",
    });

    // 名称
    slide.addText(c.name, {
      x: rightX + 0.95, y: cy + 0.1, w: 2.5, h: 0.32,
      fontFace: FONTS.head,
      fontSize: 13,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 要求
    slide.addText(c.req, {
      x: rightX + 0.95, y: cy + 0.42, w: cw - 1.15, h: 0.3,
      fontFace: FONTS.body,
      fontSize: 10,
      color: COLORS.muted,
      valign: "top",
    });

    // 进度条装饰
    const barW = (cw - 1.15) * ((i + 1) / certLevels.length);
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX + 0.95, y: cy + 0.62, w: cw - 1.15, h: 0.06,
      fill: { color: COLORS.hairline },
      line: { color: COLORS.hairline, width: 0 },
    });
    slide.addShape(pptx.ShapeType.rect, {
      x: rightX + 0.95, y: cy + 0.62, w: barW, h: 0.06,
      fill: { color: c.color },
      line: { color: c.color, width: 0 },
    });
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎培训与认证模块功能说明");
  addPageNumber(slide, "13");

  return slide;
}

// ============================================================
// 页面 14 — 产品路线图
// ============================================================
function slide14_roadmap() {
  const slide = pptx.addSlide();
  addSectionLabel(slide, "发展规划  /  PRODUCT ROADMAP");
  addAccentBar(slide, SPACING.marginX, 0.9);
  addClaimTitle(slide, "持续迭代演进，构建智能学习新范式", SPACING.marginX + 0.2, 0.82);

  addHairline(slide, SPACING.marginX, 1.6, SLIDE_W - SPACING.marginX * 2);

  // 时间线布局：4 个阶段横向排列
  const phases = [
    {
      phase: "v1.0",
      period: "已发布",
      title: "基础能力建设",
      color: COLORS.positive,
      items: [
        "多智能体协同框架",
        "知识库与 RAG 检索",
        "学习者画像建模",
        "Windows 桌面版发布",
        "幻觉检测机制",
      ],
      status: "已完成",
    },
    {
      phase: "v1.5",
      period: "规划中",
      title: "体验与性能优化",
      color: COLORS.accent,
      items: [
        "生成质量持续优化",
        "学习路径智能推荐",
        "新增学科领域覆盖",
        "桌面版性能优化",
        "批量导入导出",
      ],
      status: "进行中",
    },
    {
      phase: "v2.0",
      period: "规划中",
      title: "协作与社群",
      color: COLORS.purple,
      items: [
        "多学习者班级管理",
        "教师端备课工具",
        "学习社群互动",
        "资源共享市场",
        "移动端适配",
      ],
      status: "规划中",
    },
    {
      phase: "v3.0",
      period: "展望",
      title: "AI 原生学习 OS",
      color: COLORS.caution,
      items: [
        "全场景学习助手",
        "跨平台知识同步",
        "开放式插件生态",
        "企业级知识库接入",
        "多模态内容生成",
      ],
      status: "展望",
    },
  ];

  const phaseY = 1.85;
  const phaseW = (SLIDE_W - SPACING.marginX * 2 - SPACING.panelGap * 3) / 4;
  const phaseH = 4.2;

  // 时间线轴
  const timelineY = phaseY + 0.6;
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX + phaseW / 2, y: timelineY,
    w: SLIDE_W - SPACING.marginX * 2 - phaseW,
    h: 0.04,
    fill: { color: COLORS.hairline },
    line: { color: COLORS.hairline, width: 0 },
  });

  phases.forEach((p, i) => {
    const px = SPACING.marginX + i * (phaseW + SPACING.panelGap);

    // 时间节点圆点
    slide.addShape(pptx.ShapeType.ellipse, {
      x: px + phaseW / 2 - 0.18, y: timelineY - 0.14,
      w: 0.36, h: 0.36,
      fill: { color: p.color },
      line: { color: "FFFFFF", width: 2 },
    });

    // 阶段标签
    addSingleLineToken(slide, p.phase, {
      x: px, y: phaseY, w: phaseW, h: 0.45,
      fontFace: FONTS.head,
      fontSize: 20,
      bold: true,
      color: p.color,
      align: "center",
      valign: "middle",
    });

    // 周期标签
    slide.addShape(pptx.ShapeType.rect, {
      x: px + phaseW / 2 - 0.55, y: phaseY + 0.48, w: 1.1, h: 0.26,
      fill: { color: p.color + "" },
      line: { color: p.color, width: 0.5 },
    });
    slide.addText(p.period, {
      x: px + phaseW / 2 - 0.55, y: phaseY + 0.48, w: 1.1, h: 0.26,
      fontFace: FONTS.head,
      fontSize: 9,
      color: p.color,
      bold: true,
      align: "center",
      valign: "middle",
    });

    // 内容卡片
    addEvidencePanel(slide, px, timelineY + 0.5, phaseW, phaseH - 1.1, { headerColor: p.color });

    // 标题
    slide.addText(p.title, {
      x: px + 0.2, y: timelineY + 0.65, w: phaseW - 0.4, h: 0.35,
      fontFace: FONTS.head,
      fontSize: 12,
      color: COLORS.ink,
      bold: true,
      valign: "middle",
    });

    // 功能列表
    p.items.forEach((item, ii) => {
      const iy = timelineY + 1.1 + ii * 0.45;
      slide.addText("●", {
        x: px + 0.2, y: iy, w: 0.2, h: 0.32,
        fontFace: FONTS.body,
        fontSize: 8,
        color: p.color,
        valign: "middle",
      });
      slide.addText(item, {
        x: px + 0.4, y: iy, w: phaseW - 0.6, h: 0.32,
        fontFace: FONTS.body,
        fontSize: 9.5,
        color: COLORS.ink,
        valign: "middle",
      });
    });

    // 状态标签
    const statusY = timelineY + phaseH - 1.1 + 0.15;
    slide.addShape(pptx.ShapeType.rect, {
      x: px + 0.2, y: statusY, w: phaseW - 0.4, h: 0.32,
      fill: { color: p.color + "" },
      line: { color: p.color, width: 0.5 },
    });
    slide.addText(p.status, {
      x: px + 0.2, y: statusY, w: phaseW - 0.4, h: 0.32,
      fontFace: FONTS.head,
      fontSize: 10,
      color: p.color,
      bold: true,
      align: "center",
      valign: "middle",
    });
  });

  // 底部：当前版本信息
  slide.addShape(pptx.ShapeType.rect, {
    x: SPACING.marginX, y: 6.45,
    w: SLIDE_W - SPACING.marginX * 2, h: 0.45,
    fill: { color: COLORS.ink },
    line: { color: COLORS.ink, width: 0 },
  });

  slide.addText("当前版本：v1.0.0  ·  首个 Windows 桌面正式版已发布  ·  支持完整知识库与多智能体生成能力", {
    x: SPACING.marginX + 0.3, y: 6.45,
    w: SLIDE_W - SPACING.marginX * 2 - 0.6, h: 0.45,
    fontFace: FONTS.body,
    fontSize: 10.5,
    color: "E2E8F0",
    valign: "middle",
  });

  addFooterRule(slide);
  addSourceLine(slide, "来源：知域引擎产品路线图规划");
  addPageNumber(slide, "14");

  return slide;
}

// ============================================================
// 页面 15 — 结束页
// ============================================================
function slide15_closing() {
  const slide = pptx.addSlide();

  // 全屏深蓝背景
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: SLIDE_W, h: SLIDE_H,
    fill: { color: COLORS.ink },
    line: { color: COLORS.ink, width: 0 },
  });

  // 装饰 — 右侧网格
  const gridX = 8.5, gridY = 1.0, cellW = 0.5, cellH = 0.5;
  for (let r = 0; r < 11; r++) {
    for (let c = 0; c < 9; c++) {
      if (Math.random() > 0.7) {
        slide.addShape(pptx.ShapeType.rect, {
          x: gridX + c * cellW, y: gridY + r * cellH,
          w: cellW - 0.03, h: cellH - 0.03,
          fill: { color: "242A3D" },
          line: { color: "242A3D", width: 0 },
        });
      }
    }
  }

  // 左侧装饰线
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.8, y: 2.2, w: 0.06, h: 0.8,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 主标题
  slide.addText("感谢聆听", {
    x: 0.8, y: 3.1, w: 7, h: 1.2,
    fontFace: FONTS.head,
    fontSize: 44,
    color: "FFFFFF",
    bold: true,
  });

  // 副标题
  slide.addText("知域引擎  ·  让领域知识学习更智能、更可信", {
    x: 0.8, y: 4.4, w: 7, h: 0.5,
    fontFace: FONTS.head,
    fontSize: 16,
    color: "94A3B8",
  });

  // 分隔线
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.8, y: 5.2, w: 1.5, h: 0.03,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent, width: 0 },
  });

  // 核心成果回顾
  const achievements = [
    { value: "4", label: "智能体协同" },
    { value: "6", label: "核心功能模块" },
    { value: "3", label: "部署形态" },
    { value: "v1.0", label: "正式版本" },
  ];

  achievements.forEach((a, i) => {
    const ax = 0.8 + i * 1.6;
    addSingleLineToken(slide, a.value, {
      x: ax, y: 5.5, w: 1.4, h: 0.45,
      fontFace: FONTS.head,
      fontSize: 24,
      bold: true,
      color: COLORS.accent,
      valign: "middle",
    });
    slide.addText(a.label, {
      x: ax, y: 5.95, w: 1.4, h: 0.25,
      fontFace: FONTS.body,
      fontSize: 10,
      color: "64748B",
      valign: "middle",
    });
  });

  // 底部公司信息
  slide.addText("上海云之脑智能科技有限公司", {
    x: 0.8, y: 6.7, w: 6, h: 0.3,
    fontFace: FONTS.body,
    fontSize: 10,
    color: "475569",
  });

  return slide;
}

// ============================================================
// 生成全部幻灯片
// ============================================================
console.log("正在生成 PPT ...");

slide01_cover();
slide02_overview();
slide03_architecture();
slide04_coreModules();
slide05_multiAgent();
slide06_rag();
slide07_hallucination();
slide08_deployment();
slide09_quality();
slide10_learnerProfile();
slide11_scenarios();
slide12_privacy();
slide13_training();
slide14_roadmap();
slide15_closing();

// 输出文件
const outputPath = "c:\\Users\\22602\\Desktop\\test\\知域引擎_项目介绍.pptx";
pptx.writeFile(outputPath)
  .then(() => {
    console.log(`✅ PPT 生成成功: ${outputPath}`);
    console.log(`   共 ${pptx.slides.length} 页幻灯片`);
  })
  .catch((err) => {
    console.error("❌ 生成失败:", err);
    process.exit(1);
  });
